version: "3"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3000:3000
      - 3443:3443
    volumes:
      - ./certs:/etc/pki/ca
    environment:
      LOGGING_LEVEL: debug
      CA_CACHE_DIR: /tmp/cacache
      CA_CERTIFICATE: /etc/pki/ca/ca.pem
      CA_PRIVATE_KEY: /etc/pki/ca/ca.private.key
      CA_PUBLIC_KEY: /etc/pki/ca/ca.public.key
      USERNAME: proxy
      PASSWORD: pass