apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: credentials
        metadataPolicy: None
  refreshInterval: 60s
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Release.Name }}-credentials