apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-ingress-route-tcp
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - proxy
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .Release.Name }}-helsinki-crawler-proxy
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-ingress-route-tcps
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - proxysecure
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .Release.Name }}-helsinki-crawler-proxy
          port: 3443