apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.secret-store.server }}
      path: {{ .Values.secret-store.path }}
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.secret-store.token-ref }}
          key: token