apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.server }}
      path: {{ .Values.secretStore.path }}
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.secretStore.tokenRef }}
          key: token