apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-helsinki-crawler-proxy
  name: {{ .Release.Name }}-helsinki-crawler-proxy
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    protocol: TCP
    targetPort: 3000
  - name: https
    port: {{ .Values.service.https.port }}
    protocol: TCP
    targetPort: 3443
  selector:
    app: {{ .Release.Name }}-helsinki-crawler-proxy
  sessionAffinity: None
  type: ClusterIP